/**
 * ExportService.js
 *
 * Forensic PDF export for the Simplifii-OS Authenticity Report.
 *
 * Pulls the decrypted History of Thought log and renders a structured
 * A4 PDF with three evidentiary sections:
 *   1. Steering Map       : every AI-dial adjustment the learner made
 *   2. Bio-Stamp          : biometric presence hashes (SHA-256, no raw data)
 *   3. Audit Trail        : every AI-assist event paired with the human edit
 *
 * Requires the HistoryOfThought vault to be unlocked before calling
 * generateAuthenticityPDF(). If the vault is locked, the function throws.
 *
 * Australian English. Zero em-dashes.
 */

import { jsPDF } from 'jspdf';
import { generateAuthenticityReport, listEvents } from '../core/HistoryOfThought';

// ============================================================
// Layout constants (A4 portrait, unit: mm)
// ============================================================

const PAGE_W   = 210;
const PAGE_H   = 297;
const ML       = 20;           // left margin
const MR       = PAGE_W - 20;  // right margin
const COL_W    = PAGE_W - 40;  // usable column width
const BODY_BTM = PAGE_H - 22;  // bottom body boundary (above footer)

const FONT_SANS = 'helvetica';
const FONT_MONO = 'courier';

// ============================================================
// Colour palette (jsPDF uses 0-255 RGB)
// ============================================================

const C_SURFACE    = [9,   9,  11];   // zinc-950
const C_CARD       = [24,  24, 27];   // zinc-900
const C_RAISED     = [39,  39, 42];   // zinc-800
const C_TEXT       = [228, 228, 231]; // zinc-200
const C_MUTED      = [161, 161, 170]; // zinc-400
const C_FAINT      = [113, 113, 122]; // zinc-500
const C_EMERALD    = [16,  185, 129]; // emerald-500 (accent)
const C_EMERALD_LT = [52,  211, 153]; // emerald-300 (section headings)

// ============================================================
// Internal helpers
// ============================================================

const formatDate = (iso) => {
  if (!iso) return 'unknown';
  try {
    return new Date(iso).toLocaleString('en-AU', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit', hour12: true
    });
  } catch { return iso; }
};

const trunc = (val, maxLen = 40) => {
  const s = String(val ?? '');
  return s.length > maxLen ? s.slice(0, maxLen) + '\u2026' : s;
};

// Wraps a long string and returns the y position after the last line.
const drawWrapped = (doc, text, x, y, maxWidth, lineH = 4.5) => {
  const lines = doc.splitTextToSize(String(text || ''), maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineH;
};

// Lightweight table: header row + alternating data rows.
// Returns y after the last row.
const drawTable = (doc, headers, rows, startY, colWidths) => {
  const HEADER_H = 7;
  const ROW_H    = 6;
  const PAD_L    = 2;
  const PAD_T    = 4.5; // baseline offset within row
  let y = startY;

  // Header strip
  doc.setFillColor(...C_RAISED);
  doc.rect(ML, y, COL_W, HEADER_H, 'F');
  doc.setFont(FONT_SANS, 'bold');
  doc.setFontSize(7);
  doc.setTextColor(...C_MUTED);
  let x = ML + PAD_L;
  headers.forEach((h, i) => {
    doc.text(h, x, y + PAD_T);
    x += colWidths[i];
  });
  y += HEADER_H;

  // Data rows
  doc.setFont(FONT_MONO, 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(...C_TEXT);
  rows.forEach((row, ri) => {
    if (y > BODY_BTM) {
      doc.addPage();
      y = 20;
    }
    if (ri % 2 === 0) {
      doc.setFillColor(...C_CARD);
      doc.rect(ML, y, COL_W, ROW_H, 'F');
    }
    x = ML + PAD_L;
    row.forEach((cell, ci) => {
      const maxChars = Math.max(6, Math.floor(colWidths[ci] / 1.85));
      doc.text(trunc(cell, maxChars), x, y + PAD_T);
      x += colWidths[ci];
    });
    y += ROW_H;
  });

  return y + 4;
};

// Section heading with emerald rule.
const drawSection = (doc, title, y) => {
  if (y > BODY_BTM - 20) {
    doc.addPage();
    y = 20;
  }
  doc.setDrawColor(...C_EMERALD);
  doc.setLineWidth(0.25);
  doc.line(ML, y, MR, y);
  y += 5;
  doc.setFont(FONT_SANS, 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...C_EMERALD_LT);
  doc.text(title.toUpperCase(), ML, y);
  return y + 7;
};

// TEQSA-compliant footer on every page.
const drawFooter = (doc) => {
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setDrawColor(...C_RAISED);
    doc.setLineWidth(0.2);
    doc.line(ML, PAGE_H - 15, MR, PAGE_H - 15);
    doc.setFont(FONT_SANS, 'normal');
    doc.setFontSize(6);
    doc.setTextColor(...C_FAINT);
    doc.text(
      'Generated by Simplifii-OS. This report complies with TEQSA 2026 guidelines for transparent AI-assisted authorship.',
      ML,
      PAGE_H - 10
    );
    doc.text(`Page ${p} of ${totalPages}`, MR, PAGE_H - 10, { align: 'right' });
  }
};

// ============================================================
// Public API
// ============================================================

/**
 * generateAuthenticityPDF
 *
 * Builds and triggers a browser download of the Authenticity Report PDF.
 * The vault must be unlocked before calling this function.
 *
 * Source schema (from HistoryOfThought.generateAuthenticityReport):
 * {
 *   schema_version:  '2.0',
 *   generatedAt:     ISO8601,
 *   user_id:         string,
 *   spanDays:        number,
 *   firstEventAt:    ISO8601 | null,
 *   lastEventAt:     ISO8601 | null,
 *   totalEvents:     number,
 *   countsByType:    { [event_type: string]: number },
 *   events: [{
 *     event_id: string,
 *     type:     string,   // one of EVENT_TYPES
 *     at:       ISO8601,
 *     stream:   string,
 *     payload:  object | null
 *   }]
 * }
 */
export const generateAuthenticityPDF = async () => {
  const report = await generateAuthenticityReport();
  const { generatedAt, user_id, spanDays, totalEvents, countsByType, events } = report;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  doc.setDocumentProperties({
    title:   'Simplifii-OS Authenticity Report',
    author:  user_id,
    creator: 'Simplifii-OS',
    subject: 'AI-assisted authorship audit trail',
  });

  // Background fill (cosmetic only: PDF viewers render white by default)
  // Skipped: jsPDF background colour requires a rect over the full page which
  // conflicts with white-paper print expectations. Colours are in the text only.

  // ---- Cover ----
  let y = 18;
  doc.setFont(FONT_SANS, 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...C_TEXT);
  doc.text('Authenticity Report', ML, y);
  y += 7;

  doc.setFont(FONT_SANS, 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...C_FAINT);
  doc.text(
    `Generated: ${formatDate(generatedAt)}`,
    ML, y
  );
  y += 5;
  doc.text(
    `User: ${trunc(user_id, 30)}   |   Session span: ${spanDays} day${spanDays !== 1 ? 's' : ''}   |   Total events: ${totalEvents}`,
    ML, y
  );
  y += 5;

  // Event type summary
  const summary = Object.entries(countsByType)
    .map(([k, v]) => `${k}: ${v}`)
    .join('   ');
  doc.setFont(FONT_MONO, 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...C_MUTED);
  y = drawWrapped(doc, summary, ML, y, COL_W, 4.5);
  y += 6;

  // ---- Section 1: Steering Map ----
  y = drawSection(doc, 'Steering Map: AI Dial Adjustments', y);

  doc.setFont(FONT_SANS, 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...C_MUTED);
  doc.text(
    'Every time the learner adjusted the Grit, Scaffolding, or Literal Mode dials. Proves AI behaviour was directed by the human, not autonomous.',
    ML, y
  );
  y += 8;

  const steeringRows = events
    .filter(e => e.type === 'steering_adjusted')
    .map(e => [
      formatDate(e.at),
      e.payload?.gritLevel    ?? 'n/a',
      e.payload?.scaffoldingLevel ?? 'n/a',
      e.payload?.isLiteralMode ? 'On' : 'Off'
    ]);

  if (steeringRows.length === 0) {
    doc.setFont(FONT_SANS, 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...C_FAINT);
    doc.text('No steering adjustments recorded in this session.', ML, y);
    y += 8;
  } else {
    y = drawTable(
      doc,
      ['Timestamp', 'Grit Level', 'Scaffolding', 'Literal Mode'],
      steeringRows,
      y,
      [66, 38, 38, 28]
    );
  }

  // ---- Section 2: Bio-Stamp ----
  y = drawSection(doc, 'Bio-Stamp: Biometric Presence Proof', y);

  doc.setFont(FONT_SANS, 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...C_MUTED);
  doc.text(
    'SHA-256 hashes of biometric signals (focus level, HRV) recorded during the session. Raw values are never stored.',
    ML, y
  );
  y += 8;

  const bioRows = events
    .filter(e => e.payload?.biometric_hash)
    .map(e => [
      formatDate(e.at),
      e.type,
      trunc(e.payload.biometric_hash, 48)
    ]);

  if (bioRows.length === 0) {
    doc.setFont(FONT_SANS, 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...C_FAINT);
    doc.text(
      'No biometric signals recorded. Connect a neural band via NeuralService to generate Bio-Stamps.',
      ML, y
    );
    y += 8;
  } else {
    y = drawTable(
      doc,
      ['Timestamp', 'Event Type', 'Biometric Hash (SHA-256)'],
      bioRows,
      y,
      [50, 36, 84]
    );
  }

  // ---- Section 3: Audit Trail ----
  y = drawSection(doc, 'Audit Trail: AI Assist vs Human Edits', y);

  doc.setFont(FONT_SANS, 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...C_MUTED);
  doc.text(
    'Every AI-assist invocation paired with the nearest subsequent human text edit. Proves the learner reviewed and modified AI output.',
    ML, y
  );
  y += 8;

  const aiEvents   = events.filter(e => e.type === 'ai_assist_invoked');
  const textEdits  = events.filter(e => e.type === 'text_edit');

  if (aiEvents.length === 0) {
    doc.setFont(FONT_SANS, 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...C_FAINT);
    doc.text('No AI assist events recorded in this session.', ML, y);
    y += 8;
  } else {
    const auditRows = aiEvents.map(e => {
      const nextEdit = textEdits.find(te => te.at >= e.at);
      return [
        formatDate(e.at),
        trunc(e.payload?.mode ?? e.payload?.tool ?? 'assist', 18),
        nextEdit ? formatDate(nextEdit.at) : '(not yet)',
        nextEdit ? 'Yes' : 'No'
      ];
    });
    y = drawTable(
      doc,
      ['AI Invoked At', 'Mode / Tool', 'Human Edit At', 'Edited'],
      auditRows,
      y,
      [55, 40, 55, 20]
    );
  }

  drawFooter(doc);
  const filename = `Simplifii_Authenticity_Report_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
  return filename;
};

/**
 * getEventCount
 *
 * Returns the total number of events in the local vault without
 * decrypting. Safe to call when the vault is locked. Returns 0 on error.
 */
export const getEventCount = async () => {
  try {
    const events = await listEvents({ limit: 2000 });
    return events.length;
  } catch { return 0; }
};
